### ISSUE TITLE
Not able to save & list notification to Alarm Definitions in Grafana dashboard

### ISSUE THREAD

**Issue by maestropandy** [monasca/monasca-grafana#19]
Latest monasca/grafana:4.0.0-1.5.0, Which is having "attaching notification to alarm definition" feature.

There is issue with it currently to save & list notification, here below details

1) Created 3 types of notification email, slack, webhook
2) Under "Alarm definition" tried to map notification by manually entering Notification name manually (it should list notifications) and click saved
3) it saved without "notification" again want to update and click will save notifications. 

Expected result: While creating new "Alarm definitions" it should allow to attach notification first time itself & "alarm-actions" should list created notifications like drop down box.

Additional request: It will be great if have "match_by" having "tenant_name" & "Instance/VM name" else its hard for end user while using "Grafana" dashboard and also it creates alarms to all hosts which increases loads as well.

**Comment by matrixik** [comment]
Example:
![grafana-app-2018-09-18 09-23](https://user-images.githubusercontent.com/201930/45671030-af5b1980-bb24-11e8-96f7-4130d51d3e90.gif)

**Comment by maestropandy** [comment]
> Example:
> ![grafana-app-2018-09-18 09-23](https://user-images.githubusercontent.com/201930/45671030-af5b1980-bb24-11e8-96f7-4130d51d3e90.gif)
@matrixik would like to know in "match by" how you are getting "id, image" am getting "hostname, device, component, service" ?

**Comment by Charana123** [comment]
This issue has since been fixed
