### ISSUE TITLE
Automate enabling Monasca Apps in Grafana Dashboard like Monasca Grafana Datasource

### ISSUE THREAD

**Issue by maestropandy** [monasca/monasca-grafana#21]
Steps followed for monasca keystone entry

> ```
> 1.keystone user-create --name monasca-agent --pass password --tenant [monasca-tenant-id]
> 2.keystone user-create --name monasca --pass password --tenant [monasca-tenant-id]
> 3.keystone role-create --name monasca-agent
> 4.keystone role-create --name monasca-user
> 5.keystone user-role-add --user [monasca-agent-id] --role [monasca-agent-role-id] --tenant [monasca-tenant-id]
> 6.keystone user-role-add --user [monasca-id] --role [monasca-user-role-id] --tenant [monasca-tenant-id]
> 7.keystone service-create --type monitoring --name monasca --description "Monasca monitoring service"
> 8.keystone endpoint-create --service [service-id] --publicurl http://monasca:8080/v2.0 --internalurl http://monasca:8080/v2.0 --adminurl http://monasca:8080/v2.0
> ```

After above entry, created new user named "A" with "monasca-user" permission to tenant "myproject", logged into "grafana dashboard" with that credentials, there need to enable monasca apps under installed apps on right side of grafana UI, while doing getting error as "permission denied" then logged into grafana dashboard with "monasca" with "admin" role and enabled it.

Two things here

1) How to avoid using "monasca" user with "admin" role to enable monasca ? Because for N number of projects not possible, else alternate way is add "monasca" with "admin" role and wait for few minutes, later it will allow "A" user to enable it. it's weird and confuse end users.

2) Can we automate this enabling ? so can avoid above steps

**Comment by maestropandy** [comment]
Changed docker file to automate enable datasource type and installed apps 

> ersion: '3'
services:

  grafana:
    image: monasca/grafana:4.0.0-1.5.0
    environment:
      GF_AUTH_BASIC_ENABLED: "false"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_USERS_ALLOW_ORG_CREATE: "false"
      GF_AUTH_KEYSTONE_ENABLED: "true"
      GF_AUTH_KEYSTONE_AUTH_URL: http://192.168.56.151:5000
      GF_AUTH_KEYSTONE_VERIFY_SSL_CERT: "false"
      GF_AUTH_KEYSTONE_DEFAULT_DOMAIN: "Default"
      LOGSTASH_FIELDS: "service=grafana"
    ports:
      - "3000:3000"
    depends_on:
      - monasca

  grafana-init:
    image: monasca/grafana-init:1.3.0
    environment:
      GRAFANA_USERNAME: monasca
      GRAFANA_PASSWORD: jio@1234
      DATASOURCE_TYPE: monasca
      DATASOURCE_URL: http://monasca:8070/
      DATASOURCE_ACCESS_MODE: proxy
      DATASOURCE_AUTH: Keystone
      LOGSTASH_FIELDS: "service=grafana-init"
    depends_on:
      - grafana

But when logged into dashboard under "installed apps" Monasca is showing "Enable Now'

![image](https://user-images.githubusercontent.com/7627640/45752585-95f4c300-bc33-11e8-8d1f-b2ff099ca3ea.png)

**Comment by Charana123** [comment]
Grafana plugins currently only supports enabling via the gui web server and cannot be enabled via grafana's cli as pointed out in `https://github.com/grafana/grafana/issues/8515` and so any automated deployment tooling `https://github.com/grafana/grafana/issues/11409`.
