### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by mellitiseifeddine** [monasca/monasca-grafana#24]
i deployed Monasca using Docker but i'm not been able to create an alert using grafana dashboard 
![alert](https://user-images.githubusercontent.com/21080722/49446005-7b160180-f7d3-11e8-9815-24681f0ad6b4.png)

PS : i'm using Monasca datasource and Monasca App as show below 
![grafanapng](https://user-images.githubusercontent.com/21080722/49445970-689bc800-f7d3-11e8-9402-2387c110e0e3.png)

**Comment by dougszumski** [comment]
It's not very clear, but what you have there is a Grafana alert which doesn't integrate with Monasca, at least yet. You need to configure Monasca alerts via the interface provided by the plugin. Please see the screenshots in the README for this repo.
